"""Build a self-contained acceptance library from the canonical contract and Lua commands."""
import json,html
from pathlib import Path
R=Path(__file__).resolve().parents[1]
s=json.loads((R/'spec.json').read_text(encoding='utf8'));commands=json.loads((R/'generated/draw-commands.json').read_text(encoding='utf8'))
data=json.dumps({'spec':s,'commands':commands},ensure_ascii=False).replace('</','<\/')
page=r'''<!doctype html><meta charset="utf-8"><title>Mosaic UI contract library</title>
<style>body{margin:0;background:#14181c;color:#ecede7;font:16px system-ui;line-height:1.5}header,main{max-width:1160px;margin:auto;padding:24px}h1{margin:0;color:#ffcc65}p{max-width:80ch}select,button{background:#283139;color:inherit;border:1px solid #60727b;padding:9px;border-radius:5px;margin:4px}section{background:#20272d;padding:20px;margin:18px 0;border-radius:12px}canvas{image-rendering:pixelated;background:black;width:512px;max-width:100%;height:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px ui-monospace}#grid{display:grid;grid-template-columns:repeat(16,minmax(0,1fr));gap:5px;max-width:650px}#grid button{min-width:0;aspect-ratio:1;padding:0;margin:0;font-size:11px;border-radius:4px}#grid button[data-active="true"]{background:#97bdaa;color:#14241b}.muted{color:#afbcc3}details{margin:12px 0}summary{cursor:pointer;color:#ffcc65}.pair{display:flex;gap:32px;flex-wrap:wrap}.pair>div{flex:1;min-width:300px}</style>
<header><h1>Mosaic: grid first</h1><p>The grid performs musical actions. Norns follows the resolved action, shows its scope and offers focused editing. This library is generated from the machine contract; edit the JSON and Lua sources, not this page.</p><p class="muted">Canvas replay uses approximate browser font metrics. Native framebuffer layout and behavior acceptance remain implementation gates. These are executable drawing commands, not screenshots.</p></header>
<main><section><label>Screen <select id="screen"></select></label><label>View <select id="mode"><option value="bound">Data-bound layout</option><option value="accepted">Accepted specimen</option><option value="empty">Empty state</option></select></label><label>Field <select id="field"></select></label><div class="pair"><div><h2 id="title"></h2><canvas id="canvas" width="128" height="64"></canvas><p id="caption"></p></div><div><h3>Input contract</h3><pre id="controls"></pre></div></div></section>
<section><h2>Grid ownership</h2><div id="grid"></div><p id="cell">Hover or focus a cell for its coordinate, owner and index.</p><p class="muted">Brightness here identifies owned cells, not musical LED state. The existing grid renderer retains LED levels and phase. Doctor uses the explicit three-lane override.</p></section><section><h2>Reach and return</h2><pre id="routes"></pre><details><summary>Live binding and fields</summary><pre id="binding"></pre></details></section><section><h2>Migration and coverage</h2><pre id="migration"></pre><details><summary>Manual, lifecycle and acceptance obligations</summary><pre id="acceptance"></pre></details></section></main>
<script>const DATA=__DATA__;
const s=DATA.spec, byid=Object.fromEntries(DATA.commands.map(x=>[x.id,x]));const $=id=>document.getElementById(id);for(const [id,x]of Object.entries(s.screens)){$('screen').add(new Option(id+' · '+x.title,id))}function render(ops){let c=$('canvas').getContext('2d'),x=0,y=0,size=8;c.fillStyle='black';c.fillRect(0,0,128,64);c.lineWidth=1;for(let [op,...a]of ops){if(op==='clear'){c.fillStyle='black';c.fillRect(0,0,128,64);c.beginPath()}else if(op==='font_size'){size=a[0];c.font=size+'px monospace';c.textBaseline='alphabetic'}else if(op==='level'){let v=Math.round(a[0]/15*255);c.fillStyle=c.strokeStyle='rgb('+v+','+v+','+v+')'}else if(op==='move'){x=a[0];y=a[1];c.beginPath();c.moveTo(x,y)}else if(op==='text'||op==='text_right'){c.textAlign=op==='text_right'?'right':'left';c.fillText(String(a[0]),x,y)}else if(op==='rect'){c.beginPath();c.rect(...a)}else if(op==='circle'){c.beginPath();c.arc(a[0],a[1],a[2],0,Math.PI*2)}else if(op==='line'){c.lineTo(...a)}else if(op==='stroke')c.stroke();else if(op==='fill')c.fill()}}function draw(){let sid=$('screen').value,mode=$('mode').value,id=mode==='empty'?'empty.'+sid:mode+'.'+$('field').value;let frame=byid[id];if(frame)render(frame.ops);$('caption').textContent=id+' · '+(mode==='accepted'?'Original example values and illustrations':'All displayed fields supplied by ViewModel; fixture values for acceptance only')}function update(){let sid=$('screen').value,x=s.screens[sid];$('field').replaceChildren();for(let f of x.render.specimens)$('field').add(new Option(f,f));$('title').textContent=x.title;let rules=s.input_algebra.rules.filter(r=>!r.when.profile||[].concat(r.when.profile).includes(x.profile));$('controls').textContent='Profile: '+x.profile+'\nProvider: '+x.provider+'\nHighest matching priority wins.\n\n'+rules.filter(r=>r.when.screen?[].concat(r.when.screen).includes(sid):r.priority>=200).map(r=>r.event+' ['+JSON.stringify(r.when)+'] → '+r.effects.join(', ')).join('\n');$('binding').textContent=JSON.stringify({binding:x.binding,layout:x.live_render,fields:x.fields,inventory:s.field_contracts[x.provider]},null,2);$('routes').textContent=x.entry_flow_ids.map(id=>JSON.stringify(s.flows[id],null,2)).join('\n');$('grid').replaceChildren();let cells=s.grid.contexts[x.context]||s.grid.contexts.Channel;for(let cell of cells){let b=document.createElement('button');b.textContent=cell.index||'·';b.dataset.active=cell.control!=='inert';b.title=JSON.stringify(cell);b.onfocus=b.onmouseenter=()=>{$('cell').textContent='('+cell.x+','+cell.y+') '+cell.control+' '+(cell.index||'')};$('grid').append(b)}draw()}$('screen').onchange=update;$('mode').onchange=draw;$('field').onchange=draw;$('migration').textContent=s.migration.map(m=>m.id+' '+m.title+'\nDepends: '+m.depends.join(', ')+'\nGate: '+m.done).join('\n\n');$('acceptance').textContent=JSON.stringify(s.acceptance_matrix,null,2);update();</script>'''.replace('__DATA__',data)
(R/'generated/index.html').write_text(page,encoding='utf8')
print('Built generated/index.html')
