"""Export the runtime subset of spec.json as lib/ui_spec_data.lua.

The Lua UI reads routing data (screen registry, route maps, tasks, Doctor routes,
feature edges) from this generated table so the spec stays the only authority.
Run with --check to fail when the committed file is stale.
"""
import json, sys
from pathlib import Path

R = Path(__file__).resolve().parents[1]
REPO = R.parents[1]
OUT = REPO / 'lib' / 'ui_spec_data.lua'

SCREEN_KEYS = ['title', 'context', 'profile', 'hold_policy', 'provider', 'existing_route', 'parent']
SECTIONS = ['contexts', 'tasks', 'source_route_map', 'doctor_routes', 'feature_action_edges',
            'confirmation_contracts', 'input_algebra', 'grid', 'layout_contract', 'field_contracts']


def lua(x, indent=0):
    pad = '  ' * (indent + 1)
    if x is None: return 'nil'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x, (int, float)): return repr(x)
    if isinstance(x, str): return json.dumps(x, ensure_ascii=False)
    if isinstance(x, list):
        if not x: return '{}'
        return '{\n' + ''.join(pad + lua(v, indent + 1) + ',\n' for v in x) + '  ' * indent + '}'
    if not x: return '{}'
    return '{\n' + ''.join(pad + '[' + lua(k) + '] = ' + lua(v, indent + 1) + ',\n'
                           for k, v in x.items()) + '  ' * indent + '}'


def build():
    s = json.loads((R / 'spec.json').read_text(encoding='utf8'))
    screens = {}
    for sid, x in s['screens'].items():
        entry = {k: x.get(k) for k in SCREEN_KEYS}
        if isinstance(entry['context'], str):
            entry['context'] = [entry['context']]
        live = x.get('live_render') or {}
        entry['layout'] = live.get('layout')
        entry['art'] = live.get('art')
        entry['fields'] = [f['id'] for f in x.get('fields', [])]
        screens[sid] = entry
    data = {'version': s['version'], 'screens': screens,
            'visual_variants': sorted(s['visual_variants'])}
    for key in SECTIONS:
        data[key] = s[key]
    # The router only reads each flow's presentation outcome.
    data['flows'] = {fid: f['new'] for fid, f in s['flows'].items()}
    return ('-- Generated by docs/ui-reimplementation/tools/export_runtime.py from spec.json.\n'
            '-- Do not edit by hand.\n'
            'return ' + lua(data) + '\n')


if __name__ == '__main__':
    text = build()
    if '--check' in sys.argv:
        current = OUT.read_text(encoding='utf8') if OUT.exists() else ''
        if current != text:
            sys.exit('lib/ui_spec_data.lua is stale; run tools/export_runtime.py')
        print('ui_spec_data.lua is current')
    else:
        OUT.write_text(text, encoding='utf8')
        print('wrote', OUT.relative_to(REPO), len(text), 'bytes')
