// Reader and renderer acceptance; characterisation outside README.
const {chromium}=require("playwright"),assert=require("node:assert/strict"),fs=require("node:fs");
const {decodeScreenPixels}=require("./manual_screen_oracle.cjs");
const base=process.env.MOSAIC_MANUAL_URL||"http://localhost:8765/manual/";
(async()=>{const browser=await chromium.launch({args:["--no-sandbox"]});const report={passed:false,features:0,scenes:[],audio:[],viewports:[],checks:[]};try{
const page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(base+"#home");await page.waitForSelector("#book-home h1");assert.match(await page.locator("#book-home").textContent(),/Mosaic/);await page.locator(".skip").focus();await page.keyboard.press("Enter");assert.equal(await page.evaluate(()=>document.activeElement.id),"manual-content");assert.equal(await page.evaluate(()=>location.hash),"#home");
await page.fill("#search","install");await page.locator("#search-results a").first().click();assert.match(await page.locator("#feature-title").textContent(),/Install/);assert.equal(await page.locator("#explore").isVisible(),false);
const book=await page.request.get(base+"generated/book.json").then(r=>r.json());const optional=async name=>{const r=await page.request.get(base+"generated/"+name);return r.ok()?r.json():null;};
async function route(id,title){await page.evaluate(id=>location.hash=id,id);await page.waitForFunction(title=>document.getElementById("feature-title").textContent===title&&document.body.dataset.routeReady==="1",title);}
async function frame(output){const actual=await page.evaluate(()=>({pixels:Array.from(document.getElementById("screen").getContext("2d").getImageData(0,0,128,64).data).filter((_,i)=>i%4===0),grid:Array.from(document.querySelectorAll("#grid button")).map(b=>Number(b.dataset.level))}));assert.deepEqual(actual.pixels,decodeScreenPixels(output));assert.deepEqual(actual.grid,output.grid);}
for(const f of book.features){await route(f.id,f.title);assert.equal(await page.locator("#feature-title").textContent(),f.title);const refs=(f.scene_refs||[]).map(r=>book.scenes[typeof r==="string"?r:r.id]).filter(Boolean);assert.equal(await page.locator("#explore").isVisible(),!!refs.length);for(const [i,scene] of refs.entries()){const last=scene.steps.at(-1);await page.evaluate(hash=>location.hash=hash,f.id+"/"+scene.id+"/"+last.id);await page.waitForFunction(caption=>document.getElementById("caption").textContent===caption,last.caption);await frame(last.output);await page.selectOption("#scene",String(i));for(const [j,step] of scene.steps.entries()){if(j)await page.click("#next");assert.equal(await page.locator("#caption").textContent(),step.caption);await frame(step.output);}report.scenes.push({feature:f.id,scene:scene.id,steps:scene.steps.length});}report.features++;}
report.checks.push("All feature anchors, exact captions, captured pixels and 128 LED levels");
const audio=await optional("audio-scenes.json");for(const example of audio?.examples||[]){const feature=book.features.find(f=>example.feature_ids.includes(f.id));assert(feature,"Audio must link to an existing feature");
  // Reference pages offer only reference clips; a course clip is offered by the course chapter that owns its stage (or the chapter itself).
  const chapterOf=a=>(book.learning_path||[]).find(c=>c.id===a.course.stage||(c.stages||[]).some(st=>st.id===a.course.stage));
  let matches;if(example.course){const chapter=chapterOf(example);assert(chapter,"A course clip must belong to a course chapter: "+example.id);await page.evaluate(h=>location.hash=h,chapter.id+"/course");await page.waitForFunction(title=>document.getElementById("feature-title").textContent===title&&document.body.dataset.routeReady==="1",chapter.title);matches=audio.examples.filter(a=>a.course&&chapterOf(a)===chapter);}
  else{await route(feature.id,feature.title);matches=audio.examples.filter(a=>!a.course&&a.feature_ids.includes(feature.id));}
  assert(matches.some(a=>a.id===example.id));
  if(matches.length>1)await page.selectOption("#audio-choice",String(matches.findIndex(a=>a.id===example.id)));else assert.equal(await page.locator("#audio-choice").count(),0,"A single clip needs no chooser");
  await page.waitForFunction(title=>document.getElementById("audio-title").textContent===title&&Number.isFinite(document.getElementById("audio").duration),example.title);await page.waitForFunction(()=>document.body.dataset.routeReady==="1");const files=Array.isArray(example.files)?example.files:Object.values(example.files);const durations=await page.evaluate(async files=>{const ctx=new AudioContext();try{return await Promise.all(files.map(async file=>ctx.decodeAudioData(await fetch(file).then(r=>r.arrayBuffer())).then(a=>a.duration)));}finally{await ctx.close();}},files);for(const duration of durations)assert(duration>example.bars*4*60/example.bpm,"Encoded clip must contain the full phrase");for(const t of [1,Math.min(4,durations[0]-1)]){await page.locator("#audio").evaluate(async(a,t)=>{await a.play();a.currentTime=t;a.pause();},t);await page.waitForFunction(()=>document.getElementById("counter").textContent.startsWith("LISTEN"));const current=await page.locator("#audio").evaluate(a=>a.currentTime);const captured=example.timeline.filter(v=>v.time<=current).at(-1)||example.timeline[0];await frame(captured.output);}for(const captured of example.timeline){await page.locator("#audio").evaluate((a,t)=>new Promise(resolve=>{const target=t+.00001;if(Math.abs(a.currentTime-target)<.000001){a.dispatchEvent(new Event("seeked"));resolve();return;}a.addEventListener("seeked",resolve,{once:true});a.currentTime=target;}),captured.time);await frame(captured.output);}report.audio.push({id:example.id,formats:files.length,durations,frames:example.timeline.length});}
report.checks.push("Every musical example decodes, seeks and paints its own captured timeline");
for(const routeId of ["home","learn","workflow","reference","quick","cookbook"]){await page.evaluate(id=>location.hash=id,routeId);await page.waitForSelector("#book-home:not([hidden])");assert(await page.locator("#book-home a").count()>0);}
for(const width of [1440,768,390]){await page.setViewportSize({width,height:900});await page.goto(base+"#home");await page.waitForSelector("#book-home h1");await page.evaluate(()=>window.scrollTo({top:0,behavior:"instant"}));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const header=await page.locator(".topbar").boundingBox(),headline=await page.locator("#book-home h1").boundingBox();assert(headline.y>=header.y+header.height,"Header must not overlap the homepage headline");assert(await page.locator("#book-home .book-recipe").count()<=6);await page.screenshot({path:"manual/evidence/book-viewport-"+width+".png"});await page.screenshot({path:"manual/evidence/book-browser-"+width+".png",fullPage:true});report.viewports.push(width);}report.checks.push("Every reader route is populated; responsive home without overflow");assert.deepEqual(errors,[]);report.passed=true;
}finally{await browser.close();fs.writeFileSync("manual/evidence/book-browser-report.json",JSON.stringify(report,null,2)+"\n");}console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exitCode=1;});
