-- Presentation router (docs/ui-reimplementation, UI03).
--
-- A literal Lua port of docs/ui-reimplementation/tools/model.py `step`: the
-- input algebra selects exactly one rule per event (highest priority, ties are
-- errors) and its effects run in order. Navigation effects change presentation
-- state here. Every other effect is an adapter command: the router hands it to
-- `hooks[op]` and never performs or mocks the musical result itself.
--
-- lib/tests/lib/ui_router_tests.lua replays traces generated by model.py and
-- requires identical states, effect lists and rule ids.

local ui_router = {}

local FRAME = {"screen", "field_id", "target", "generation"}

local function copy(value)
  if type(value) ~= "table" then return value end
  local result = {}
  for key, item in pairs(value) do result[key] = copy(item) end
  return result
end

local function contains(list, value)
  for _, item in ipairs(list) do if item == value then return true end end
  return false
end

-- Guards are equality, or membership when the guard value is a list.
local function matches(guard, state)
  for key, expected in pairs(guard or {}) do
    local actual = state[key]
    if type(expected) == "table" then
      if not contains(expected, actual) then return false end
    elseif actual ~= expected then
      return false
    end
  end
  return true
end
ui_router.matches = matches

local Router = {}
Router.__index = Router

-- hooks: {[effect] = function(router, event, payload, edge)} for adapter commands.
function ui_router.new(spec, hooks, state)
  local self = setmetatable({spec = spec, hooks = hooks or {}}, Router)
  self.state = state or ui_router.initial()
  return self
end

function ui_router.initial(screen, context)
  return {
    screen = screen or "C01", context = context or "Channel", native = false, modal = false,
    held = false, shift = false, dirty = false, playing = false, family = "masks",
    field_kind = "value", field_id = "trig", target = {channel = 1, song_slot = 1, step_set = {}},
    return_stack = {}, generation = 0
  }
end

function Router:screen_entry(screen_id)
  local screen = self.spec.screens[screen_id or self.state.screen]
  if not screen then error("unknown screen " .. tostring(screen_id or self.state.screen)) end
  return screen
end

function Router:contexts(screen_id)
  return self:screen_entry(screen_id).context
end

-- state plus the derived registry keys guards may read (profile, provider, hold_policy).
function Router:view(extra)
  local screen = self:screen_entry()
  local view = {}
  for key, value in pairs(self.state) do view[key] = value end
  view.profile, view.provider, view.hold_policy = screen.profile, screen.provider, screen.hold_policy
  for key, value in pairs(extra or {}) do view[key] = value end
  return view
end

function Router:select(event)
  local view = self:view()
  local best, top, tied = nil, nil, {}
  for _, rule in ipairs(self.spec.input_algebra.rules) do
    if rule.event == event and matches(rule.when, view) then
      if top == nil or rule.priority > top then
        best, top, tied = rule, rule.priority, {rule.id}
      elseif rule.priority == top then
        tied[#tied + 1] = rule.id
      end
    end
  end
  if not best then error("unhandled input " .. event) end
  if #tied > 1 then error("ambiguous rules " .. table.concat(tied, ",")) end
  return best
end

local DOCTOR_KEYS = {"doctor_state", "modal_operation", "draft", "preview", "playing"}

-- Resolves a Rhythm Doctor screen from spec.doctor_routes alone.
function ui_router.doctor_route(spec, payload, flow_id)
  for _, key in ipairs(DOCTOR_KEYS) do
    if payload[key] == nil then error("doctor payload missing " .. key) end
  end
  local found = {}
  for _, row in ipairs(spec.doctor_routes.rows) do
    if matches(row.when, payload) then found[#found + 1] = row end
  end
  if #found ~= 1 then
    local ids = {}
    for _, row in ipairs(found) do ids[#ids + 1] = row.id end
    error("doctor_routes rows " .. table.concat(ids, ","))
  end
  local flow = spec.doctor_routes.flows[flow_id]
  for _, override in ipairs(flow and flow.overrides or {}) do
    if payload.outcome == override.outcome and contains(override.rows, found[1].id) then return override.screen end
  end
  return found[1].screen
end

function Router:task_rows(payload)
  local view = self:view(payload)
  local rows = {}
  for _, row in ipairs(self.spec.tasks.rows[self.state.screen] or {}) do
    local allowed = row.contexts == nil or contains(row.contexts, self.state.context)
    if allowed and matches(row.visible_when, view) then rows[#rows + 1] = row end
  end
  return rows
end

local function row_screen(row, context)
  if type(row.screen) == "table" then return row.screen[context] end
  return row.screen
end
ui_router.row_screen = row_screen

local function find_edge(spec, screen, field_id)
  for _, edge in ipairs(spec.feature_action_edges) do
    if edge.from == screen and edge.field_id == field_id then return edge end
  end
end

local FAMILY_NAVIGATION = {C01 = {["E1-"] = "C01", ["E1+"] = "C02"}, C02 = {["E1-"] = "C01", ["E1+"] = "N01"}}

-- Applies one event. Returns the effect list (each {op, target}) and the rule id.
-- A failed event (unhandled input, tie, bad context) leaves the state unchanged.
function Router:step(event, payload)
  local saved = self.state
  self.state = copy(saved)
  local ok, ops, rule_id = pcall(self.apply_event, self, event, payload or {})
  if not ok then
    self.state = saved
    error(ops, 0)
  end
  return ops, rule_id
end

function Router:apply_event(event, payload)
  local s = self.state
  local spec = self.spec
  local rule = self:select(event)
  local ops = {}
  local function family() return s.family == "parameters" and "C02" or "C01" end
  local function primary() return s.context == "Channel" and family() or spec.contexts[s.context] end
  local function push()
    local frame = {}
    for _, key in ipairs(FRAME) do frame[key] = copy(s[key]) end
    s.return_stack[#s.return_stack + 1] = frame
  end
  local function invalidate() s.return_stack = {}; s.generation = s.generation + 1 end
  local function set_family_from_screen()
    if s.screen == "C01" or s.screen == "C02" then s.family = s.screen == "C02" and "parameters" or "masks" end
  end

  local queue = {}
  for _, op in ipairs(rule.effects) do queue[#queue + 1] = op end
  local edge
  while #queue > 0 do
    local op = table.remove(queue, 1)
    ops[#ops + 1] = {op = op, target = copy(s.target)}
    if op == "owner.invoke_selected" then
      -- Static action edges: the selected stable field id picks the edge; its effects run in order.
      edge = find_edge(spec, s.screen, s.field_id)
      if edge then
        for index = #edge.effects, 1, -1 do table.insert(queue, 1, edge.effects[index]) end
      end
    elseif op == "owner.open_translated_route" then
      s.screen = edge.to
    elseif op == "owner.enter_root" then
      if not s.held then s.screen = edge.to; s.return_stack = {} end
    elseif op == "return.push" then
      push()
    elseif op == "return.invalidate" then
      invalidate()
    elseif op == "return.parent" or op == "return.restore_if_generation_matches" then
      local frames = {}
      for _, frame in ipairs(s.return_stack) do
        if frame.generation == s.generation then frames[#frames + 1] = frame end
      end
      if #frames > 0 then
        local frame = table.remove(frames)
        s.screen, s.field_id, s.target = frame.screen, copy(frame.field_id), copy(frame.target)
        s.return_stack = frames
      elseif self:screen_entry().profile ~= "feature" then
        s.screen = primary()
      end
    elseif op == "scope.set_held" then
      s.held = true; s.target.step_set = copy(payload.steps or {})
    elseif op == "scope.update_full_set" then
      s.target.step_set = copy(payload.steps or {})
    elseif op == "scope.clear" then
      s.held = false; s.target.step_set = {}
    elseif op == "scope.restore_family" then
      s.screen = family()
    elseif op == "scope.follow" then
      if s.context == "Channel" and self:screen_entry().hold_policy == "follow_family" then s.screen = family() end
    elseif op == "family.navigate" then
      s.screen = FAMILY_NAVIGATION[s.screen][event]
      set_family_from_screen()
    elseif op == "family.switch_clamped" then
      s.screen = event == "E1+" and "C02" or "C01"
      s.family = s.screen == "C02" and "parameters" or "masks"
    elseif op == "tasks.channel_exit_or_clamp" then
      s.screen = event == "E1-" and "C02" or "N01"
    elseif op == "tasks.open" then
      s.screen = spec.tasks.navigators[s.context]
    elseif op == "tasks.enter_selected" then
      local chosen
      for _, row in ipairs(self:task_rows(payload)) do
        if row.id == payload.task then chosen = row end
      end
      if not chosen or chosen.screen == nil then error("task not enterable " .. tostring(payload.task)) end
      s.screen = row_screen(chosen, s.context)
      set_family_from_screen()
    elseif op == "feature.return_then_tasks" then
      local root = self:screen_entry().provider == "merge" and "M02" or "H01"
      if s.dirty or #s.return_stack > 0 or s.screen ~= root then
        s.dirty = false; s.return_stack = {}; s.screen = root
      else
        s.screen = "N01"
      end
    elseif op == "owner.cancel_unapplied" then
      s.dirty = false
    elseif op == "native.open" then
      s.native = true
    elseif op == "native.close" then
      s.native = false
    elseif op == "route.C07" then
      s.screen = "C07"
    elseif op == "outcome.follow" then
      self:follow(payload, push, invalidate)
    elseif op == "owner.preserve_key_edge" then
      if event == "K1.down" or event == "K1.up" then s.shift = event == "K1.down" end
    end
    local hook = self.hooks[op]
    if hook then hook(self, event, payload, edge) end
  end
  if not contains(self:contexts(s.screen), s.context) then
    error("context " .. s.context .. " cannot show " .. s.screen)
  end
  return ops, rule.id
end

-- One resolved grid outcome sets context, screen and target together.
function Router:follow(payload, push, invalidate)
  local s = self.state
  local flow = self.spec.flows[payload.flow_id]
  if not flow then error("unknown flow " .. tostring(payload.flow_id)) end
  local view = self:view(payload)
  if flow.routes == "doctor_routes" then ui_router.doctor_route(self.spec, payload, payload.flow_id) end
  local options = {}
  for _, alternative in ipairs(flow.alternatives or {}) do
    if matches(alternative.when, view) then options[#options + 1] = alternative end
  end
  table.sort(options, function(a, b) return a.priority > b.priority end)
  if #options > 1 and options[1].priority == options[2].priority then error("ambiguous outcome") end
  local chosen = options[1] or flow
  local navigation = chosen.navigation or flow.navigation
  if flow.invalidates_return then s.dirty = false; invalidate() end
  if navigation == "temporary" and not s.held then push() end
  if navigation ~= "retain" then
    s.context = chosen.context or flow.context or s.context
    s.screen = chosen.screen
    if payload.target ~= nil then s.target = copy(payload.target) end
  end
end

return ui_router
