-- Characterisation outside the manual: the presentation router must agree with
-- the executable presentation model (docs/ui-reimplementation/tools/model.py).
-- The traces are generated by tools/router_traces.py and cover every rule.

local ui_router = include("mosaic/lib/ui_router")
local spec = include("mosaic/lib/ui_spec_data")
local json = include("mosaic/lib/helpers/json")

local STATE_KEYS = {"screen", "context", "native", "modal", "held", "shift", "dirty", "family",
  "field_kind", "field_id", "target", "return_stack", "generation"}

local function copy(value)
  if type(value) ~= "table" then return value end
  local result = {}
  for key, item in pairs(value) do result[key] = copy(item) end
  return result
end

local function load_traces()
  local handle = assert(io.open("../../docs/ui-reimplementation/generated/router-traces.json", "r"))
  local text = handle:read("*a")
  handle:close()
  return json.decode(text)
end

local function merge(into, changes)
  for key, value in pairs(changes or {}) do into[key] = copy(value) end
end

local function project(state)
  local result = {}
  for _, key in ipairs(STATE_KEYS) do result[key] = state[key] end
  return result
end

function test_ui_router_replays_every_model_trace()
  local traces = load_traces()
  local rules, steps = {}, 0
  for walk_index, walk in ipairs(traces.walks) do
    local expected = copy(walk.start)
    local router = ui_router.new(spec, {}, copy(walk.start))
    for step_index, entry in ipairs(walk.steps) do
      local where = "walk " .. walk_index .. " step " .. step_index .. " " .. entry.event .. " on " .. expected.screen
      merge(expected, entry.set)
      merge(router.state, entry.set)
      local ok, ops, rule = pcall(router.step, router, entry.event, copy(entry.payload))
      if entry.error then
        luaunit.assert_false(ok, where .. " should fail")
      else
        luaunit.assert_true(ok, where .. ": " .. tostring(ops))
        luaunit.assert_equals(rule, entry.rule, where)
        local names = {}
        for _, op in ipairs(ops) do names[#names + 1] = op.op end
        luaunit.assert_equals(names, entry.ops, where)
        merge(expected, entry.diff)
        rules[rule] = true
      end
      luaunit.assert_equals(project(router.state), project(expected), where)
      steps = steps + 1
    end
  end
  local covered = 0
  for _ in pairs(rules) do covered = covered + 1 end
  luaunit.assert_equals(covered, #spec.input_algebra.rules)
  luaunit.assert_true(steps > 10000)
end

function test_ui_router_zero_rules_or_ties_are_errors()
  local router = ui_router.new({input_algebra = {rules = {
    {id = "a", event = "E1+", when = {}, effects = {}, priority = 1},
    {id = "b", event = "E1+", when = {}, effects = {}, priority = 1}
  }}, screens = spec.screens}, {})
  luaunit.assert_error_msg_contains("ambiguous rules a,b", function() router:select("E1+") end)
  luaunit.assert_error_msg_contains("unhandled input E2+", function() router:select("E2+") end)
end

function test_ui_router_failed_event_leaves_state_unchanged()
  local router = ui_router.new(spec, {})
  local before = copy(router.state)
  luaunit.assert_false(pcall(router.step, router, "grid.outcome", {flow_id = "missing"}))
  luaunit.assert_equals(router.state, before)
end

function test_ui_router_adapter_commands_reach_hooks_in_order()
  local seen = {}
  local router = ui_router.new(spec, setmetatable({}, {__index = function(_, op)
    return function() seen[#seen + 1] = op end
  end}))
  local ops = router:step("E3+")
  local names = {}
  for _, op in ipairs(ops) do names[#names + 1] = op.op end
  luaunit.assert_equals(seen, names)
end

function test_ui_router_every_doctor_input_resolves_to_one_screen()
  local inputs = spec.doctor_routes.inputs
  local count = 0
  for _, state in ipairs(inputs.doctor_state.values) do
    for _, modal in ipairs(inputs.modal_operation.values) do
      for _, draft in ipairs(inputs.draft.values) do
        for _, preview in ipairs(inputs.preview.values) do
          for _, playing in ipairs({false, true}) do
            local screen = ui_router.doctor_route(spec, {doctor_state = state, modal_operation = modal,
              draft = draft, preview = preview, playing = playing})
            luaunit.assert_not_nil(spec.screens[screen])
            count = count + 1
          end
        end
      end
    end
  end
  luaunit.assert_equals(count, 8 * 4 * 4 * 2 * 2)
end
