const {chromium}=require('C:/Users/andy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),crypto=require('crypto');const out={checks:[],errors:[]},base='http://localhost:8785/manual/';
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{for(const width of [1440,390]){const context=await b.newContext({viewport:{width,height:900}}),p=await context.newPage();p.on('pageerror',e=>out.errors.push(e.message));const go=async hash=>{await p.goto('about:blank');await p.goto(base+'#'+hash);await p.waitForFunction(()=>document.body.dataset.routeReady==='1');};const save=async(label,data)=>out.checks.push({width,label,...data});
await go('home');await save('home',{tagline:/step by step|a piece at a time/i.test(await p.locator('body').innerText()),text:(await p.locator('main').innerText()).slice(0,550)});await p.screenshot({path:path.join(__dirname,'home-viewport-'+width+'.png')});
await p.getByRole('searchbox').fill('Harmony');await p.locator('#search-results a').first().waitFor();await save('exact-search',{first:await p.locator('#search-results a').first().getAttribute('href'),text:(await p.locator('#search-results').innerText()).slice(0,850)});await p.locator('#search-results a').first().focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>location.hash==='#harmony'&&document.activeElement?.id==='feature-title');await save('search-focus',{active:await p.evaluate(()=>document.activeElement.id),query:await p.getByRole('searchbox').inputValue(),resultsVisible:await p.locator('#search-results').isVisible()});await p.getByRole('searchbox').fill('poly');await save('partial-search',{text:(await p.locator('#search-results').innerText()).slice(0,650)});await p.getByRole('searchbox').fill('luaunit');await save('private-search',{text:await p.locator('#search-results').innerText()});
for(const route of ['midi-panic','locks','midi-controller-options','honor-scale-rotations','honour-scale-transpose','performance-management']){await go(route);const summaries=p.locator('details>summary');const names=await summaries.allTextContents();for(let i=0;i<names.length;i++)if(/Panic and connected|After clearing|option-enabled|When playback/.test(names[i])){await summaries.nth(i).click();await save('expanded-noise',{route,title:names[i],text:await summaries.nth(i).locator('..').innerText()});await summaries.nth(i).scrollIntoViewIfNeeded();await p.screenshot({path:path.join(__dirname,'noise-'+route+'-'+width+'.png')});}}
await go('first-sound/course');await p.getByText('Follow the controls one at a time',{exact:true}).click();await save('course-guide',{buttons:await p.locator('#explore button').allTextContents()});await p.getByRole('button',{name:'Show result',exact:true}).last().click();await p.waitForTimeout(250);await save('course-result',{focus:await p.evaluate(()=>document.activeElement.id),step:await p.locator('#step-title').innerText(),text:(await p.locator('main').innerText()).slice(0,600)});
await go('masks');await p.locator('.instruments').scrollIntoViewIfNeeded();const geom=()=>p.evaluate(()=>({pressed:document.querySelector('#norns-layout').getAttribute('aria-pressed'),pad:document.querySelector('#grid button').getBoundingClientRect().width,grid:document.querySelector('#grid').getBoundingClientRect().width,wrap:document.querySelector('.grid-wrap').clientWidth,doc:document.documentElement.scrollWidth,width:innerWidth}));await save('standard-grid',await geom());await p.screenshot({path:path.join(__dirname,'standard-'+width+'.png')});await p.locator('#norns-layout').click();await save('shield',await geom());await p.screenshot({path:path.join(__dirname,'shield-'+width+'.png')});await p.reload();await p.waitForFunction(()=>document.body.dataset.routeReady==='1');await save('shield-persistence',await geom());await p.locator('#enlarged-grid-controls summary').click();await p.waitForFunction(()=>document.querySelector('.instruments').classList.contains('grid-enlarged'));await save('enlarged-grid',await geom());await p.locator('#grid button').first().focus();for(let i=0;i<15;i++)await p.keyboard.press('ArrowRight');await save('grid-keyboard',{focused:await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),scroll:await p.locator('.grid-wrap').evaluate(e=>e.scrollLeft)});await p.screenshot({path:path.join(__dirname,'enlarged-'+width+'.png')});
await go('lfos-and-modulation');await save('modest-lfo',{step:await p.locator('#step-title').innerText()});await p.getByRole('link',{name:'Set up a clocked LFO at full depth',exact:true}).click();await p.waitForFunction(()=>location.hash.includes('toolkit-clocked-lfo-menu-clock'));await p.waitForTimeout(250);await save('advanced-lfo',{title:await p.locator('#step-title').innerText()});
await go('recording/voice-leading-revoice');await p.locator('audio').waitFor({state:'attached'});await p.waitForFunction(()=>document.querySelector('audio').readyState>=1);await save('recording',{heading:await p.locator('main h1:visible').innerText(),audio:await p.locator('audio').evaluate(e=>({duration:e.duration,readyState:e.readyState,controls:e.controls})),text:(await p.locator('main').innerText()).slice(0,3500)});await p.locator('audio').evaluate(async e=>{e.muted=true;await e.play()});await p.locator('a[href="#recordings"]').last().click();await p.waitForFunction(()=>document.querySelector('#book-home h1')?.textContent==='Recordings');await p.waitForTimeout(200);await save('audio-teardown',{playing:await p.locator('audio').evaluateAll(es=>es.filter(e=>!e.paused).length)});
await p.goto('http://localhost:8785/cheat_sheet.html');await p.locator('#find').fill('polyperc');await save('quick-polyperc',{text:await p.locator('body').innerText(),doc:await p.evaluate(()=>document.documentElement.scrollWidth)});await p.locator('#find').fill('masks');await save('quick-masks',{text:(await p.locator('body').innerText()).slice(0,1200)});await p.screenshot({path:path.join(__dirname,'quick-'+width+'.png')});await context.close();}}catch(e){out.errors.push(e.stack);process.exitCode=1;}finally{await b.close();for(const f of ['book.js','generated/reader-index.json','index.html'])out[f]=crypto.createHash('sha256').update(Buffer.from(await(await fetch(base+f)).arrayBuffer())).digest('hex');fs.writeFileSync(path.join(__dirname,'interaction-observations.json'),JSON.stringify(out,null,2));}console.log(JSON.stringify(out));})();





