name: Run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-tests-on-Ubuntu:
    name: Run tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - run: ./test.sh
